use [BagShop]

insert into [dbo].[ShoppingItems] values (N'Сумка поясная', N'Размеры: 20×10×2см, Максимальная длина ремешка - 110см', N'Эко-кожа, хлопок(подкладка)', N'Протирать влажной тканью, немного смоченной в мыльном растворе. Не стирать.', 320, '')
insert into [dbo].[ShoppingItems] values (N'Сумка', N'Размеры: 22×14×2см, Максимальная длина ремешка - 110см', N'Эко-кожа, хлопок(подкладка)', N'Протирать влажной тканью, немного смоченной в мыльном растворе. Не стирать.', 350, '')
insert into [dbo].[ShoppingItems] values (N'Рюкзак', N'Размеры: 38×26×10м, Максимальная длина ремешков - 100см', N'Эко-кожа, полиестер(подкладка)', N'Протирать влажной тканью, немного смоченной в мыльном растворе. Не стирать.', 550, '')

insert into [dbo].[ColourPreviews] values (N'Голубой')
insert into [dbo].[ColourPreviews] values (N'Зеленый')
insert into [dbo].[ColourPreviews] values (N'Бежевый')
insert into [dbo].[ColourPreviews] values (N'Серебристый')
insert into [dbo].[ColourPreviews] values (N'Белый')
insert into [dbo].[ColourPreviews] values (N'Черный')

insert into [dbo].[Colours] values (1, 1)
insert into [dbo].[Colours] values (2, 1)
insert into [dbo].[Colours] values (3, 1)
insert into [dbo].[Colours] values (4, 1)
insert into [dbo].[Colours] values (5, 1)
insert into [dbo].[Colours] values (6, 1)
insert into [dbo].[Colours] values (1, 2)
insert into [dbo].[Colours] values (2, 2)
insert into [dbo].[Colours] values (3, 2)
insert into [dbo].[Colours] values (4, 2)
insert into [dbo].[Colours] values (5, 2)
insert into [dbo].[Colours] values (6, 2)
insert into [dbo].[Colours] values (4, 3)
insert into [dbo].[Colours] values (5, 3)
insert into [dbo].[Colours] values (6, 3)

insert into [dbo].[ColourPhotoes] values (7)
insert into [dbo].[ColourPhotoes] values (7)
insert into [dbo].[ColourPhotoes] values (7)
insert into [dbo].[ColourPhotoes] values (8)
insert into [dbo].[ColourPhotoes] values (8)
insert into [dbo].[ColourPhotoes] values (8)
insert into [dbo].[ColourPhotoes] values (10)
insert into [dbo].[ColourPhotoes] values (10)
insert into [dbo].[ColourPhotoes] values (11)
insert into [dbo].[ColourPhotoes] values (11)
insert into [dbo].[ColourPhotoes] values (11)
insert into [dbo].[ColourPhotoes] values (3)
insert into [dbo].[ColourPhotoes] values (3)
insert into [dbo].[ColourPhotoes] values (4)
insert into [dbo].[ColourPhotoes] values (4)
insert into [dbo].[ColourPhotoes] values (15)
insert into [dbo].[ColourPhotoes] values (15)
